### ISSUE TITLE
Introduce new rubric

### ISSUE THREAD

**Issue by marble** [TYPO3-Documentation/DocsTypo3Org-Homepage#11]
How to cover "Frequently asked topics"?

- TYPO3 caching
- structural elements (like gridelements)
- custom content elements
- responsive images
- ckeditor
- code of conduct
  https://www.typo3.net/artikel/kennt-ihr-den-typo3-code-of-conduct/
- ...
 Some topics are typically answered in blogposts.

Just some ideas: Frequently asked topics, TYPO3 journal, magazines, Info Guide, What people ask

**Comment by sypets** [comment]
Is this now covered by: https://docs.typo3.org/typo3cms/TellMeSomethingAbout/ ?
