### ISSUE TITLE
Branch out other version branches?

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/DocsTypo3Org-Homepage#111]
Instead of adding links to other versions on indiviudal pages which must be updated manually, it would be consistent to create version branches for this repo as well and be able to automatically link to other versions of manuals.

**Comment by susannemoog** [comment]
I'm not sure if this is (currently) worth it, as this has a lot of side effects on how the home page is rendered and deployed. I would rather tackle this while merging repositories instead - I'll close this issue for now but keep it in mind for the restructuring of repositories project.
