### ISSUE TITLE
case insensitive extension search

### ISSUE THREAD

**Issue by josefglatz** [TYPO3-Documentation/DocsTypo3Org-Homepage#143]
Hi folks,

My super duper apple smartphone has this nice feature of writing the first letter as uppercase in an input field. There might be other reasons why the search for extensions needs to be case insensitive.

Is that something which can be done easily in [WebRootResources/js/extensions-search.js](https://github.com/TYPO3-Documentation/DocsTypo3Org-Homepage/blob/master/WebRootResources/js/extensions-search.js) ?

**Comment by linawolf** [comment]
The legacy search will be removed, search in the TER or on composer
