### ISSUE TITLE
Should we create a "Getting started with extension development" tutorial?

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/DocsTypo3Org-Homepage#149]
The "Extbase book" used to be the walkthrough for extension development, but there are 2 problems:

* It is about writing (mostly) plugins with Extbase / Fluid in a very specific way. There are lots of extension which have a different goal and do not use Extbase or even Fluid
* There are some things missing, e.g. setting up the development environment, giving the beginner some information, what types of extensions there are, when to use Extbase when not, having a complete walkthrough of creating a small extension without the (unnecessary) overhead of walking through explanations of Extbase.

Some things are already listed in the "Extension Development" chapter in TYPO3 Explained, starting with '"STEPS TOWARDS CREATING AN EXTENSION" but this is not something you can just point a beginner to and then rest assured they have everything they need.

**Comment by susannemoog** [comment]
I think this is too much to handle with a simple issue. I agree that we should write (or rewrite) the whole area of extension development in the documentation (see also your issues about this in the extbase/fluid guide). This is a whole project in and off itself. I would close this (single) issue here, and hope that "someone" picks up the rewrite project at some point in the future.
