### ISSUE TITLE
Logo on "Core Documentation" missing

### ISSUE THREAD

**Issue by cweiske** [TYPO3-Documentation/DocsTypo3Org-Homepage#151]
https://docs.typo3.org/Home/References.html misses the top left logo. It only shows the fallback "TYPO3 Logo".

Linked URL is https://docs.typo3.org/_static/img/typo3-logo.svg and that gives a 404

**Comment by vanshika123malhotra** [comment]
I think the issue has been resolved as I was not able to reproduce the error that has been mentioned by @cweiske
