### ISSUE TITLE
Rendering problem?

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/DocsTypo3Org-Homepage#157]
There is an error which seems to be already fixed in the source:

![image](https://user-images.githubusercontent.com/13206455/118496282-43417100-b724-11eb-9332-fb23cc09fcc1.png)

* should be "adminpanel", not dashboard twice 
* Also, it still links to master, not 10.4

* https://docs.typo3.org/Home/SystemExtensions.html
* https://github.com/TYPO3-Documentation/DocsTypo3Org-Homepage/edit/master/Documentation/Home/SystemExtensions.rst

**Comment by susannemoog** [comment]
This has been fixed now, I'm going to close this issue :)
