### ISSUE TITLE
issue with php file

### ISSUE THREAD

**Issue by anujaunds** [TYPO3-Documentation/DocsTypo3Org-Homepage#16]
i just try to use php file with create and lib object but it's now working my typo3 ver is 8^. my typoscript code is # Add bellow typoscrip in setup.ts
lib.jobs = USER
lib.jobs {

    # Define external PHP Script file path
    includeLibs = fileadmin/functions.php

    # Call user function
    userFunc = getData->GetNewsCountInCat

}.
could you please let me how to get php code in template file

**Comment by liayn** [comment]
Go to the Install Tool. Select "Upgrade Analysis" from the menu and search for `includeLibs`.
You will find

> Breaking: #73514 - TypoScript property "includeLibs" removed

So change your code to a PHP class and use `USER_INT` in your typoscript instead.

Please close the ticket here as this is the bugtracker for the documentation and not a help forum.
Please reach out to either of the platforms documented at https://typo3.org/help/ instead. Thanks.
