### ISSUE TITLE
docs.typo3.org broken when adblocker is installed. 

### ISSUE THREAD

**Issue by fawmi** [TYPO3-Documentation/DocsTypo3Org-Homepage#186]
This issue is global accross all TYPO3 websites, and not related to docs.typo3.org but affects typo3 docs as well. Also I could not find another appropriate repository to create an issue for it. 

All the TYPO3 websites are broken when adblocker is installed. 

![image](https://user-images.githubusercontent.com/16363859/145876537-dc09c8f3-1afd-4c37-ab05-17c7459887c5.png)

**Comment by mbrodala** [comment]
Please get in touch with the developer of the adblocker or add exceptions to your settings. There is unlikely something we can do about this.

**Comment by marble** [comment]
I have AdBlock installed and don't encounter problems.
