### ISSUE TITLE
References to PackageStates.php should be removed / changed for main + 11.5

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/DocsTypo3Org-Homepage#198]
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/11.4/Feature-94996-ConsiderAllComposerInstalledExtensionsAsActive.html

* the file is no longer required
* the file is no longer generated
* all extensions will be considered active
* use php vendor/bin/typo3 extensions:setup to setup extensions

grep -r PackageStates.php */Documentation

- TYPO3CMS-Exceptions/Documentation/Exceptions/1338996122.rst:the :file:`typo3conf/PackageStates.php` manually.
- TYPO3CMS-Exceptions/Documentation/Exceptions/1382276561.rst::file:`typo3conf/PackageStates.php` and remove the part which belongs to the
- TYPO3CMS-Exceptions/Documentation/Exceptions/1382276561.rst:If deleting :file:`PackageStates.php` is no option, try using the
- TYPO3CMS-Exceptions/Documentation/Exceptions/1365429673.rst:Open :file:`typo3conf/PackageStates.php`, look up the extension key and
- TYPO3CMS-Exceptions/Documentation/Exceptions/1365429673.rst::file:`PackageStates.php`, trying to recover the old version did help in my
- TYPO3CMS-Exceptions/Documentation/Exceptions/1365429673.rst:array part or add it to your file :file:`PackageStates.php`:
- TYPO3CMS-Exceptions/Documentation/Exceptions/1365429673.rst:You must have a backup copy of the file typo3conf/PackageStates.php .
- TYPO3CMS-Exceptions/Documentation/Exceptions/1365429673.rst:Restore a file PackageStates.php which is compatible under TYPO3 6.2.
- TYPO3CMS-Guide-Installation/Documentation/MigrateToComposer/MigrationSteps.rst:for generating the file :file:`typo3conf/PackageStates.php`.
- TYPO3CMS-Guide-Installation/Documentation/MigrateToComposer/MigrationSteps.rst:| :file:`public/typo3conf/PackageStates.php`           |
- TYPO3CMS-Reference-CoreApi-sypets/Documentation/ExtensionArchitecture/HowTo/ExtensionManagement.rst:   :file:`PackageStates.php` file. Extensions are loaded in the order they appear in this list.
- TYPO3CMS-Reference-CoreApi-sypets/Documentation/ExtensionArchitecture/HowTo/ExtensionManagement.rst:the order they were listed in :file:`PackageStates.php` in legacy installations.
- TYPO3CMS-Reference-CoreApi-sypets/Documentation/Testing/WritingFunctional.rst:`typo3conf/ext` for third party extensions, creates a :file:`PackageStates.php` and then uses the
- TYPO3CMS-Tutorial-GettingStarted-sypets/Documentation/Extensions/LegacyManagement.rst:extensions manually with :file:`PackageStates.php` as a last resort, see :ref:`uninstall-extension-manually`
- TYPO3CMS-Tutorial-GettingStarted-sypets/Documentation/Extensions/LegacyManagement.rst:Since LTS8 this can be done by removing the extensions configuration from the file :file:`PackageStates.php`
- TYPO3CMS-Tutorial-GettingStarted-sypets/Documentation/Extensions/LegacyManagement.rst:#. Open the file :file:`typo3conf/PackageStates.php`
- TYPO3CMS-Tutorial-GettingStarted-sypets/Documentation/Extensions/LegacyManagement.rst:      :caption: typo3conf/PackageStates.php
-

**Comment by brotkrueml** [comment]
AFAIK that only applies to composer-based installations. Legacy installations rely on the PackageStates.php also in v11 and main.

**Comment by linawolf** [comment]
Yes it is still used in non-composer mode even in TYPO3 13
