### ISSUE TITLE
Broken links in "How to create translations" container on startpage

### ISSUE THREAD

**Issue by peterkraume** [TYPO3-Documentation/DocsTypo3Org-Homepage#203]
There are 2 broken links in the container "How to create translations" on https://docs.typo3.org/

- 2nd bullet "Supported languages" => https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/Localization/Languages.html
- 5th bullet "Internationalization and localization in TYPO3 Explained" => https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/Localization/Index.html

I tried to make the changes by myself but unfortunately I have no clue how this linking works.

**Comment by brotkrueml** [comment]
Hej Peter,
thanks for the hint. The chapters were moved from "Internationalization" to "Localization". Appearently, no redirects are in place. I just re-rendered the triggering of the page and now the links are correct.

**Comment by peterkraume** [comment]
Thx for taking care!
