### ISSUE TITLE
Bug: Copy&Paste button in code blocks adds line numbers

### ISSUE THREAD

**Issue by christophlehmann** [TYPO3-Documentation/DocsTypo3Org-Homepage#207]
https://docs.typo3.org/p/georgringer/news/main/en-us/Tutorials/BestPractice/Routing/Index.html#id5

Copy:
<img width="906" alt="copy" src="https://user-images.githubusercontent.com/4953689/207715522-1570d5a0-46f8-4cad-925b-39ff886e6d26.png">
Paste:
<img width="384" alt="paste" src="https://user-images.githubusercontent.com/4953689/207715519-4fa28287-c1d3-4601-9cf2-bc19defcd726.png">

**Comment by fnagel** [comment]
Related to https://github.com/TYPO3-Documentation/sphinx_typo3_theme/issues/184

**Comment by brotkrueml** [comment]
It is fixed since June 19, 2023. Only manuals rendered since then have this change available.
