### ISSUE TITLE
Rework start page and menu structure

### ISSUE THREAD

**Issue by marble** [TYPO3-Documentation/DocsTypo3Org-Homepage#22]

**Comment by tmotyl** [comment]
An idea:
Let's make a home page display tiles with different documentation.
See this example of documentation overview from other project:
https://www.odoo.com/documentation/11.0/index.html

**Comment by marble** [comment]
An idea:
https://support.mozilla.org/de/products/thunderbird

This is nice looking too:
![grafik](https://user-images.githubusercontent.com/307057/41714724-9a595682-7551-11e8-8c99-21ced20207d4.png)


It would be cool, if we had TYPO3 icons for: R=Reference, T=Tutorial, H=Howto, G=Guide ...

**Comment by marble** [comment]
Odoo:
![grafik](https://user-images.githubusercontent.com/307057/41715182-e7998b00-7552-11e8-8e39-79d96eb6522b.png)

**Comment by sypets** [comment]
I like the general idea of using tiles with images but would prefer it if the images fit the topic and are not just pretty to look at.

**Comment by susannemoog** [comment]
See #160

**Comment by susannemoog** [comment]
Leaving this issue open for now as we want to add icons to the cards we now use.

**Comment by DavidBruchmann** [comment]
Is the decoration with the icons still desired or can this be closed @linawolf, @brotkrueml ?

**Comment by linawolf** [comment]
Lets close for now
