### ISSUE TITLE
Back end Extension Links

### ISSUE THREAD

**Issue by rmilenov** [TYPO3-Documentation/DocsTypo3Org-Homepage#223]
I'm encountering a strange Problem with some extensions. In the complete absence of any problem in typo3 log, i can't seem to change 
pages in the Back end Modules in some extension ( Extension Builder, Luxletter in this instance).
I've noticed not proper generated link otherwise i don't really have a clue why is this happening.

### Current behavior

[Generated link](https://webserver.rado/typo3/index.php?route=%2Fmodule%2Flux%2FLuxletterLuxletter&token=17b0ca4a2f10aeff35c1744bd76c3d6bab7777c5&tx__%5Baction%5D=list&tx__%5Bcontroller%5D=Newsletter)

### Expected behavior/output

[Expected link](https://webserver.rado/typo3/index.php?route=%2Fmodule%2Flux%2FLuxletterLuxletter&token=17b0ca4a2f10aeff35c1744bd76c3d6bab7777c5&tx_luxletter_lux_luxletterluxletter%5Baction%5D=list&tx_luxletter_lux_luxletterluxletter%5Bcontroller%5D=Newsletter)

### TYPO3 versions

10.4.37

**Comment by brotkrueml** [comment]
@rmilenov Please note, that this is the repository for the TYPO3 documentation home page and not for problems with custom TYPO3 installations. Please ask on stackoverflow.com (with tag #typo3) or on [typo3.slack.com](https://typo3.org/community/meet/chat-slack) instead for support.
