### ISSUE TITLE
Remove meaningless "PHP" tooltips

### ISSUE THREAD

**Issue by simonschaufi** [TYPO3-Documentation/DocsTypo3Org-Homepage#243]
Tooltip with explanation what PHP means is visible on any "code"  like for example here: https://docs.typo3.org/m/typo3/reference-tca/12.4/en-us/ColumnsConfig/Type/File/Index.html#columns-file if you hover your mouse over `inline` which just doesn't make any sense.

### Links

https://docs.typo3.org/m/typo3/reference-tca/12.4/en-us/ColumnsConfig/Type/File/Index.html#columns-file

**Comment by fe-hicking** [comment]
Yes, this is done for all languages like TS, JS, PHP etc to distinguish in which language a code snippet is posted, because the visual formatting is identical and else wouldnt be clear if a variable for example is TS, fluid, PHP or something else.

So this is intentional.

**Comment by fe-hicking** [comment]
(Where a specific language doesnt make sense, the rst formating would just need to use `something` instead of :php:`something` on a case-by-case basis. Individual PRs for that are welcome, as combing through that takes quite some effort 😬)

**Comment by simonschaufi** [comment]
Ok.

**Comment by simonschaufi** [comment]
It would have been clear to me if it would say 'PHP code' instead of just PHP

**Comment by garvinhicking** [comment]
This is a valid suggestion. I'll discuss it in our slack channel!
