### ISSUE TITLE
Rework left navigation panel for startpage 

### ISSUE THREAD

**Issue by foliengriller** [TYPO3-Documentation/DocsTypo3Org-Homepage#28]
The following changes should only apply to welcome document
- Remove duplicate link to "home"
- Remove search because it is missleading and does not search the whole documentation 
- Remove version selector if there is only one version available

![screenshot-2018-6-23 guides and tutorials welcome documentation](https://user-images.githubusercontent.com/24498435/41808664-33f14fbc-76e1-11e8-8637-3fd6d7c68c1c.png)

**Comment by sypets** [comment]
Before / After image to visualize what gets changed:

![neu](https://user-images.githubusercontent.com/13206455/41808821-a1ee385c-76e3-11e8-9465-f147cf09bcf0.png)

**Comment by DanielSiepmann** [comment]
This is partly linked to https://github.com/TYPO3-Documentation/T3DocTeam/issues/1

**Comment by sypets** [comment]
Related: https://github.com/TYPO3-Documentation/t3SphinxThemeRtd/issues/81

**Comment by sypets** [comment]
This has now been implemented:

* search removed for homepage
* version links not displayed for homepage
* "Welcome" with link above search box was removed.
