### ISSUE TITLE
no verb in sentence

### ISSUE THREAD

**Issue by marble** [TYPO3-Documentation/DocsTypo3Org-Homepage#4]
@fsuter It looks like the verb is missing here:

.. sidebar:: New to TYPO3 CMS?

   If you are new to TYPO3 CMS, please start by reading the
   :ref:`Tutorials <tutorials>`, which will help you progressively
   your knowledge of TYPO3 CMS.

**Comment by fsuter** [comment]
For me this is correct. It is a headline and does not need to be a full sentence. Actually I think that add "Are you" at the beginning would be redundant.

**Comment by marble** [comment]
Ah, now I understand. You mean "..., which will help you progressively WITH your knowledge of TYPO3 CMS". I thought you meant "... help you progressively enrich (or something) your knowledge of TYPO3 CMS.

The way it is right now feels wrong to me. Maybe we should ask someone.

**Comment by marble** [comment]
The headline is fine without "Are you" of course. I mean that "help you progressively ((word missing)) your knowledge

**Comment by fsuter** [comment]
Ah sorry, I concentrated on the wrong part. Indeed, there's a word missing. I think I was meaning to use "increase". Will correct when I have a few minutes.
