### ISSUE TITLE
Many documentation pages in google lead to a not found error

### ISSUE THREAD

**Issue by kathangeorg** [TYPO3-Documentation/DocsTypo3Org-Homepage#57]
Many links to the documentation page https://docs.typo3.org/ in the google index have stopped working recently.

Example: https://docs.typo3.org/typo3cms/ExtbaseGuide/Fluid/ViewHelper/Case.html

**Comment by sypets** [comment]
Thank you. This is a known issue, that concerns the ViewHelper reference. We are working on a solution. Sorry for the inconvenience.

Please use the generated ViewHelper reference: https://docs.typo3.org/typo3cms/ViewHelperReference/

**Comment by sypets** [comment]
Is fixed.
