### ISSUE TITLE
Question: when pages are printed as pdf they heading seem to be rendered as pictures

### ISSUE THREAD

**Issue by kludikovsky** [TYPO3-Documentation/DocsTypo3Org-Homepage#6]
When I try to print the pages as pdf, it seems that the headings are rendered as pictures.
Basically this isn't aproblem, but when I try to do some highlighting those headings (h1, h2, ...) can't be hightlighted.

I've tried this with different pdf-creators and browsers, and got always the same results. Even when trying to include the font.

Any idea how this can be overcome?

*Background Info*
Sometimes it's easier to print the relevant pages to a pdf and highlight those steps which need to be executed upfront.
The headings are relevant as they hold sometimes param's/settings.

**Comment by liayn** [comment]
You are aware that there is a download button to retrieve a PDF version of a documentation?
Click on the version selector in the right bottom corner of the sidebar.

**Comment by kludikovsky** [comment]
Ever tryed it here
https://docs.typo3.org/typo3cms/extensions/multishop/Administrator/Typo3BackendSection/Index.html#jquery-t3jquery-notice

And this in not the only one.

**Comment by kludikovsky** [comment]
**Cause**
As far as I could figure out now, is the `font-family: Share;`, where Share is a Web Font as far as I understand it.

**Solution**
Injected a `font-family: Arial, "Helvetica Neue", Helvetica, sans-serif;` and the problem is gone.

**Comment by liayn** [comment]
Okay, this is the old layout. I'm pretty sure Martin will not dig very much into this anymore.
Extensions are still using the old layout currently unfortunately.
Core documentation is already in the new layout and the PDF seems to work there.

**Comment by marble** [comment]
@kludikovsky Thanks for reporting. The "old layout" has a lot of problems - the plan is to switch to the new layout everywhere soon (February). Please be patient. Maybe you're interested to join the documentation team? Keep an eye on the #typo3-documentation channel at https://typo3.slack.com/messages/typo3-documentation/ To join: https://forger.typo3.org/slack

**Comment by kludikovsky** [comment]
OK, I joined #typo3-documentation channel . Not sure if I can be of great help :-)

**Comment by marble** [comment]
Well, don't worry: Sometimes even only complaining helps. From that point of view everybody can help :-)) Great you joined! Take your time.
