### ISSUE TITLE
Link "TYPO3 CMS Core ChangeLog (latest)" broken

### ISSUE THREAD

**Issue by fsaris** [TYPO3-Documentation/DocsTypo3Org-Homepage#7]
The link to `TYPO3 CMS Core ChangeLog (latest)` is broken
https://docs.typo3.org/typo3cms/References/Index.html#references

Not sure where this should link to. https://docs.typo3.org/typo3cms/extensions/core/8-dev ?

**Comment by cweiske** [comment]
Also, "Changelog 8" links to https://docs.typo3.org/typo3cms/extensions/core/8.7/ but only lists 7.x changes.

**Comment by cweiske** [comment]
This is fixed now, see chat log:

> Martin Bless [3:48 PM] 
> Hhm, we have a clone of TYPO3.CMS there. The working dir wasn't clean. Could be the reason. I've fixed that and triggered rebuilding. Let's see what happens. Is running now - will take some minutes.
> 
> Mathias wild Brodala [4:52 PM] 
> @martin.bless Seems to be back to normal, thanks for fixing. :thumbsup:
