### ISSUE TITLE
Integration SkillDisplay into docs

### ISSUE THREAD

**Issue by DanielSiepmann** [TYPO3-Documentation/DocsTypo3Org-Homepage#77]
We should discuss with the education committee how we could integrate SkillDisplay into the docs.

We have different opportunities / ideas:

- [ ] "Florian Weiss" told me we could add buttons to pages that contain a link to SkillDisplay, to mark a skill as finished.
- [ ] The education committee has his own skill display instance (as staging system). Maybe we can work with this instance as first test integration
- [ ] It should be possible to link to Skills from the docs. This can be used to Guide users. This way we might be able to tackle https://github.com/TYPO3-Documentation/DocsTypo3Org-Homepage/issues/36, https://github.com/TYPO3-Documentation/DocsTypo3Org-Homepage/issues/35 and https://github.com/TYPO3-Documentation/DocsTypo3Org-Homepage/issues/22

The following has to happen:

- [ ] Establish workflow with Education committee to update links at SkillDisplay. E.g. some links don't contain version numbers, but are for a specific TYPO3 Version. Also linking to latest should be avoided, due to changes of content with next TYPO3 releases.

**Comment by linawolf** [comment]
Asked Florian Weiss on Slack about this, Dont know his Git Handle
